version: 2.1
defaults: &defaults
  docker:
  - image: circleci/node:10.14.1
  working_directory: ~/project
#####################################################
# Commands
#####################################################
commands:
  check_result:
    description: Get last command result
    parameters:
      step_name:
        type: string
    steps:
      - run:
          name: << parameters.step_name >>
          command: |
            RESULT=$?
            if [ $RESULT != 0 ];
            then
              echo 'Test failed'
              exit 1
            else
              echo 'Test passed'
              exit 0
            fi
#####################################################
# Jobs
#####################################################
jobs:
  dependencies_install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
           - v1-dependencies-{{ checksum "package.json" }}
           - v1-dependencies-
      - run:
          name: Dependencies Install
          command: |
            npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/project
          paths:
          - ./
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Build System
          command: |
            npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
          - ./
#####################################################
# Workflow
#####################################################
workflows:
  version: 2
  check_package:
    jobs:
      - dependencies_install
      - build:
          requires:
            - dependencies_install
